version: '3'

services:
  web:
    build: ./
    container_name: users
    image: users:latest
    command: python user.py
    restart: always
    ports:
      - "80:80"
    environment:
      - TEAM_NAME=CC_0788_0794_0847

